---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - postgresql-client
    - libpq-dev
    - libjpeg8-dev
    - python-pip
    - python-psycopg2
    - git

- name: Clone Django Repository
  git: repo=https://github.com/icarrera/django-imager.git dest={{ django_home }} force=yes

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ django_home }}/requirements.txt"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Get DB Password
  include_vars: secrets.yml


# - name: Set DB URL
#   set_fact: 
#     db_url: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"



- name: Run Migrations
  environment:
    SECRET_KEY: "{{ SECRET_KEY }}"
    DB_NAME: "{{ DB_NAME }}"
    DB_USER: "{{ DB_USER }}"
    DB_PASSWORD: "{{ DB_PASSWORD }}"
    DB_HOST: "{{ DB_HOST }}"
    DB_PORT: "{{ DB_PORT }}"
    PEMAIL: "{{ PEMAIL }}"
    IMAGER_EMAIL_HOST_USER: "{{ IMAGER_EMAIL_HOST_USER }}"
    IMAGER_EMAIL_HOST_PASSWORD: "{{ IMAGER_EMAIL_HOST_PASSWORD }}"
  django_manage:
    app_path: "{{ django_home }}/imagersite"
    settings: imagersite.settings
    command: migrate

- name: Collect Static Files
  environment:
    SECRET_KEY: "{{ SECRET_KEY }}"
    DB_NAME: "{{ DB_NAME }}"
    DB_USER: "{{ DB_USER }}"
    DB_PASSWORD: "{{ DB_PASSWORD }}"
    DB_HOST: "{{ DB_HOST }}"
    DB_PORT: "{{ DB_PORT }}"
    PEMAIL: "{{ PEMAIL }}"
    IMAGER_EMAIL_HOST_USER: "{{ IMAGER_EMAIL_HOST_USER }}"
    IMAGER_EMAIL_HOST_PASSWORD: "{{ IMAGER_EMAIL_HOST_PASSWORD }}"
  django_manage:
    app_path: "{{ django_home }}/imagersite"
    settings: imagersite.settings
    command: collectstatic


# - name: Change Permissions on Media Files Experiment
#   file:
#     path: "{{ django_home }}/imagersite/media/"
#     mode: u=rwX,g=rX,o=rX
#     owner: www-data
#     sudo: yes
#     sudo_user: root
#     recurse: yes

- name: Change Media files ownership
  sudo: yes
  file: path="{{ django_home }}/imagersite/media/" state=directory mode=0755 owner=www-data


